name: Generate Snake Animation

on:
  schedule:
    # every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/github-contributions-snake@v3
        with:
          github_user_name: CB010717
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake.gif
